version: "2.13.0"
services:
  telegram-api:
    platform: linux/x86_64
    image: aiogram/telegram-bot-api
    environment:
      TELEGRAM_STAT: ${TELEGRAM_STAT}
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
    volumes:
      - type: bind
        source: ${STORAGE_PATH}/telegram-bot-api-data
        target: /var/lib/telegram-bot-api
    ports:
      - "127.0.0.1:8093:8081"
      - "127.0.0.1:8094:8082"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    restart: always
  purr-purr:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./Dockerfile
    cpu_count: 8
    depends_on:
      - telegram-api
    runtime: nvidia
    environment:
      TZ: "Europe/Moscow"
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility,video"
      DEV: ${DEV}
      BOT_DEBUG: ${BOT_DEBUG}
      BOT_TOKEN: ${BOT_TOKEN}
      CHAT_ID_CHANNEL_LOG: ${CHAT_ID_CHANNEL_LOG}
      DIR_BOT: "/bot-data"
      DIR_DB: "/bot-db"
      DOWNLOAD_LIMIT: ${DOWNLOAD_LIMIT}
      TG_API_ENDPOINT: telegram-api:8081
      TG_PATH_LOCAL: "/telegram-bot-api-data"
      WELCOME_VIDEO_ID: ${WELCOME_VIDEO_ID}
    volumes:
      - type: bind
        source: ${STORAGE_PATH}/bot-data
        target: /bot-data
      - type: bind
        source: ${STORAGE_PATH}/telegram-bot-api-data
        target: /telegram-bot-api-data
      - type: bind
        source: ${STORAGE_PATH}/bot-db
        target: /bot-db
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    restart: unless-stopped